export const statusOptions = [
  "Not Started",
  "In Progress",
  "Pending",
  "On Hold",
  "Completed",
  "Cancelled",
];

export const priorityOptions = ["Low", "Medium", "High", "Urgent"];

export const blockerSeverityOptions = ["Low", "Medium", "High", "Critical"];

export const blockerCategories = [
  "Approval",
  "Supplier",
  "Payment",
  "Contract",
  "Licensing / IP Approval",
  "Construction / Installation",
  "Design / Creative",
  "Logistics / Supply Chain",
  "Manpower",
  "Timeline",
  "Other",
];

export const roles = ["Admin", "Project Manager", "Team Member", "Viewer"];

export const defaultUsers = [
  {
    id: "user-admin",
    name: "Mai Admin",
    email: "admin@example.com",
    role: "Admin",
    created_at: "2026-06-01T09:00:00.000Z",
  },
  {
    id: "user-pm",
    name: "Narin Project",
    email: "pm@example.com",
    role: "Project Manager",
    created_at: "2026-06-02T09:00:00.000Z",
  },
  {
    id: "user-team",
    name: "Ploy Team",
    email: "team@example.com",
    role: "Team Member",
    created_at: "2026-06-03T09:00:00.000Z",
  },
  {
    id: "user-viewer",
    name: "Viewer Guest",
    email: "viewer@example.com",
    role: "Viewer",
    created_at: "2026-06-04T09:00:00.000Z",
  },
];

export const defaultCategories = [
  ["cat-docs", "Documentation", "#4f46e5"],
  ["cat-construction", "Construction / Installation", "#0f766e"],
  ["cat-marketing", "Marketing", "#db2777"],
  ["cat-supply", "Supply Chain", "#0891b2"],
  ["cat-licensing", "Licensing / IP Approval", "#7c3aed"],
  ["cat-finance", "Finance / Payment", "#ca8a04"],
  ["cat-legal", "Legal / Contract", "#475569"],
  ["cat-vendor", "Vendor Management", "#ea580c"],
  ["cat-operation", "Operation", "#16a34a"],
  ["cat-ticketing", "Ticketing", "#2563eb"],
  ["cat-merch", "Merchandise", "#c026d3"],
  ["cat-partnership", "Partnership / Sponsorship", "#0d9488"],
  ["cat-design", "Design / Creative", "#e11d48"],
  ["cat-production", "Event Production", "#9333ea"],
  ["cat-other", "Other", "#64748b"],
].map(([id, name, color]) => ({
  id,
  name,
  color,
  created_at: "2026-06-01T09:00:00.000Z",
}));

const now = "2026-06-30T09:00:00.000Z";

export const defaultProjects = [
  {
    id: "project-one-piece",
    name: "One Piece Emotion Exhibition",
    description:
      "Immersive character-driven exhibition journey with production, IP approval, ticketing, and merchandise workstreams.",
    start_date: "2026-10-15",
    owner_id: "user-pm",
    created_at: now,
    updated_at: now,
  },
  {
    id: "project-jade",
    name: "Pursuit of Jade Exhibition",
    description:
      "Premium cultural exhibition with partner coordination, design approvals, and installation milestones.",
    start_date: "2026-11-20",
    owner_id: "user-admin",
    created_at: now,
    updated_at: now,
  },
];

export const defaultMainTasks = [
  {
    id: "main-ip-approval",
    project_id: "project-one-piece",
    title: "IP Approval Package",
    category_id: "cat-licensing",
    owner_id: "user-pm",
    status: "In Progress",
    due_date: "2026-07-18",
    progress: 45,
    notes: "Character art, copy, and layout approval set.",
    created_at: now,
    updated_at: now,
  },
  {
    id: "main-installation",
    project_id: "project-one-piece",
    title: "Installation Planning",
    category_id: "cat-construction",
    owner_id: "user-team",
    status: "Pending",
    due_date: "2026-08-20",
    progress: 20,
    notes: "Waiting for finalized space measurements.",
    created_at: now,
    updated_at: now,
  },
  {
    id: "main-jade-design",
    project_id: "project-jade",
    title: "Gallery Design Freeze",
    category_id: "cat-design",
    owner_id: "user-admin",
    status: "In Progress",
    due_date: "2026-07-25",
    progress: 50,
    notes: "Design team preparing final mood boards and lighting references.",
    created_at: now,
    updated_at: now,
  },
  {
    id: "main-jade-sponsors",
    project_id: "project-jade",
    title: "Sponsor Confirmation",
    category_id: "cat-partnership",
    owner_id: "user-pm",
    status: "On Hold",
    due_date: "2026-07-05",
    progress: 15,
    notes: "Commercial terms under review.",
    created_at: now,
    updated_at: now,
  },
];

export const defaultSubTasks = [
  {
    id: "sub-key-art",
    main_task_id: "main-ip-approval",
    project_id: "project-one-piece",
    title: "Submit key art for approval",
    category_id: "cat-licensing",
    owner_id: "user-pm",
    status: "In Progress",
    priority: "High",
    due_date: "2026-07-08",
    progress: 60,
    latest_update: "Licensor requested alternate crop for entrance wall.",
    attachment_url: "https://example.com/one-piece-key-art",
    blocker_status: "Yes",
    blocker_detail: "Awaiting final approval on hero artwork crop.",
    blocker_category: "Approval",
    blocker_owner_id: "user-pm",
    blocker_expected_resolution_date: "2026-07-03",
    blocker_severity: "High",
    created_at: now,
    updated_at: now,
  },
  {
    id: "sub-character-copy",
    main_task_id: "main-ip-approval",
    project_id: "project-one-piece",
    title: "Finalize character copy",
    category_id: "cat-docs",
    owner_id: "user-team",
    status: "Completed",
    priority: "Medium",
    due_date: "2026-06-28",
    progress: 100,
    latest_update: "All English and Thai copy approved.",
    attachment_url: "",
    blocker_status: "No",
    blocker_detail: "",
    blocker_category: "",
    blocker_owner_id: "",
    blocker_expected_resolution_date: "",
    blocker_severity: "",
    created_at: now,
    updated_at: now,
  },
  {
    id: "sub-site-measurement",
    main_task_id: "main-installation",
    project_id: "project-one-piece",
    title: "Confirm site measurement",
    category_id: "cat-construction",
    owner_id: "",
    status: "Pending",
    priority: "Urgent",
    due_date: "2026-06-25",
    progress: 15,
    latest_update: "Venue access window is still unconfirmed.",
    attachment_url: "",
    blocker_status: "Yes",
    blocker_detail: "Venue has not confirmed access date.",
    blocker_category: "Timeline",
    blocker_owner_id: "user-admin",
    blocker_expected_resolution_date: "2026-06-27",
    blocker_severity: "Critical",
    created_at: now,
    updated_at: now,
  },
  {
    id: "sub-gallery-layout",
    main_task_id: "main-jade-design",
    project_id: "project-jade",
    title: "Approve gallery layout",
    category_id: "cat-design",
    owner_id: "user-team",
    status: "In Progress",
    priority: "High",
    due_date: "2026-07-12",
    progress: 50,
    latest_update: "Curatorial team asked for clearer artifact sight lines.",
    attachment_url: "https://example.com/jade-layout",
    blocker_status: "No",
    blocker_detail: "",
    blocker_category: "",
    blocker_owner_id: "",
    blocker_expected_resolution_date: "",
    blocker_severity: "",
    created_at: now,
    updated_at: now,
  },
  {
    id: "sub-lighting-test",
    main_task_id: "main-jade-design",
    project_id: "project-jade",
    title: "Lighting test with artifact replicas",
    category_id: "cat-production",
    owner_id: "user-pm",
    status: "Not Started",
    priority: "Medium",
    due_date: "",
    progress: 0,
    latest_update: "Pending layout freeze before vendor booking.",
    attachment_url: "",
    blocker_status: "No",
    blocker_detail: "",
    blocker_category: "",
    blocker_owner_id: "",
    blocker_expected_resolution_date: "",
    blocker_severity: "",
    created_at: now,
    updated_at: now,
  },
  {
    id: "sub-sponsor-contract",
    main_task_id: "main-jade-sponsors",
    project_id: "project-jade",
    title: "Sign lead sponsor contract",
    category_id: "cat-legal",
    owner_id: "user-admin",
    status: "On Hold",
    priority: "Urgent",
    due_date: "2026-07-01",
    progress: 20,
    latest_update: "Legal waiting for payment clause confirmation.",
    attachment_url: "",
    blocker_status: "Yes",
    blocker_detail: "Sponsor requested revised cancellation clause.",
    blocker_category: "Contract",
    blocker_owner_id: "user-admin",
    blocker_expected_resolution_date: "2026-07-02",
    blocker_severity: "Critical",
    created_at: now,
    updated_at: now,
  },
];

export const defaultUpdates = [
  {
    id: "update-key-art-1",
    sub_task_id: "sub-key-art",
    update_detail: "Submitted first artwork set to licensor.",
    next_action: "Receive comments and prepare revised crop.",
    blocker: "Awaiting IP approval.",
    updated_by: "user-pm",
    created_at: "2026-06-29T10:30:00.000Z",
  },
  {
    id: "update-measurement-1",
    sub_task_id: "sub-site-measurement",
    update_detail: "Venue team is checking access calendar.",
    next_action: "Escalate to venue operations manager.",
    blocker: "Access date not confirmed.",
    updated_by: "user-admin",
    created_at: "2026-06-30T08:00:00.000Z",
  },
  {
    id: "update-sponsor-1",
    sub_task_id: "sub-sponsor-contract",
    update_detail: "Sponsor returned redlines to legal.",
    next_action: "Review cancellation clause with finance.",
    blocker: "Contract wording unresolved.",
    updated_by: "user-admin",
    created_at: "2026-06-30T11:15:00.000Z",
  },
];

export const initialState = {
  users: defaultUsers,
  categories: defaultCategories,
  projects: defaultProjects,
  mainTasks: defaultMainTasks,
  subTasks: defaultSubTasks,
  updates: defaultUpdates,
};
